#!/usr/bin/env sh

# Secondary Database
SETTINGS_FILE='/app/html/sites/all/settings/base.settings.php'
sed -i "s|LEVEL2_DATABASE_USER|$LEVEL2_DATABASE_USER|g" $SETTINGS_FILE
sed -i "s|LEVEL2_DATABASE_PASSWORD|$LEVEL2_DATABASE_PASSWORD|g" $SETTINGS_FILE
sed -i "s|LEVEL2_DATABASE_HOST|$LEVEL2_DATABASE_HOST|g" $SETTINGS_FILE
sed -i "s|LEVEL2_DATABASE|$LEVEL2_DATABASE|g" $SETTINGS_FILE
